In [1]:
import os
if os.path.basename(os.getcwd()) == "inspeccion":
    os.chdir("..")
    
import pandas as pd
from utils.funciones_filtrado import tipo_nulo_unicos_x_columna

In [2]:
base_productos = pd.read_excel('productos.xlsx')
base_productos.head()

  producto_id        producto categoria   tamaño activo
0        P001       Americano      café    Chico   True
1        P001       Americano      Café   Grande   True
2        P002           Latte      Café    Chico   True
3        P003  Latte Vainilla      cafe    Chico   True
4        P004      Cappuccino      Café  Mediano   True

In [3]:
no_registros, no_columnas = base_productos.shape
print(f"Número de productos registrados: {no_registros}, número de columnas de la tabla: {no_columnas}")

Número de productos registrados: 18, número de columnas de la tabla: 5

Podemos notar que en la columna 'producto_id' tenemos un id repetido y eso es algo que no debería de suceder debido a que al hacer algún tipo de cruce con otro tabla, vamos a obtener resultados incorrectos, ya que como son dos productos diferentes, asociados a un mismo id, las ventas, stock se asociaran a un sólo producto generando valores más altos y al otro producto tendrá valores bajos o nulos.

De igual manera en la columna 'categoría' observamos que existen diferencias, debido a que en le primer registro se escribió 'café' y en el segundo 'Café', que de igual manera al hacer análisis de esa columna generará errores, ya que, se trarán como diferentes cuando deben ser los mismos.

In [4]:
inspeccion = tipo_nulo_unicos_x_columna(base_productos)
inspeccion

,columna,tipo de dato,cantidad de valores nulos,cantidad de valores unicos
0,producto_id,object,1,16
1,producto,object,0,17
2,categoria,object,0,11
3,tamaño,object,0,6
4,activo,object,0,4

Los tipos de datos son consistentes, ya que al menos en esta tabla no esperamos otro tipo de dato, como númerico o de fecha.

Observamos que la columna 'producto_id' aparte de tener un datos repetido, tiene un valor nulo, lo que provoca que la cantidad de valores unicos 16 no coincida con la cantidad de productos registrados en la tabla, que son 18.

También en la columna 'categoria', notamos que sus valores únicos no son 4, como esperamos en la ficha técnica, ya que tenemos 11 valores, es decir, como observamos anteriormente, 'café' y 'Café' los tomará como diferentes, por lo que para otras categorias probablemente se escribió de diferente forma, generando nuevas categorías.

Además en la columna 'activo' notamos que hay 4 valores únicos, cuando yo supondría que sólo fueran 2, verdadero y falso (True y False), posiblemente existan registros mal escritos de la misma forma que sucedió con la columna 'categoría'

In [5]:
id_repetidos = base_productos['producto_id'].value_counts()
id_repetidos

producto_id
P001    2
P002    1
P003    1
P004    1
P005    1
P006    1
P007    1
P008    1
P009    1
P010    1
P011    1
P013    1
P014    1
P015    1
P016    1
P017    1
Name: count, dtype: int64

In [6]:
id_repetidos[id_repetidos > 1]

producto_id
P001    2
Name: count, dtype: int64

Realizamos la inspección de la cantidad de veces que se repite un id y si hay id's que se repiten más de una vez, y notamos que es el producto con id P001

In [7]:
base_productos[base_productos['producto_id'] == 'P001']

  producto_id   producto categoria  tamaño activo
0        P001  Americano      café   Chico   True
1        P001  Americano      Café  Grande   True

In [8]:
base_productos[base_productos['producto_id'].isna()]

   producto_id   producto categoria    tamaño activo
12         NaN  Croissant  Alimento  Unitario   True

Verificamos el id que se repite y el producto que no tiene id

In [5]:
#vemos todos los valores unicos de la columna 'categoria'
base_productos['categoria'].unique()

array(['café', 'Café', 'cafe', 'CAFÉ', 'Frío', 'frio', 'Te', 'Té',
       'Alimento', 'alimento', 'Alimentos'], dtype=object)

Notamos que efectivamente, hay 4 formas en las que se escribió 'Café', 2 formas que se escribió 'Frío', 2 de 'Té' y 3 de 'Alimento', generando las 11 "categorías" falsas

In [6]:
#vemos todos los valores unicos de la columna 'activo'
base_productos['activo'].unique()

array([True, False, 'VERDADEOR', 'FALSE'], dtype=object)

Notamos que aparte de 'True' y 'False' que ya son los valores booleanos que identifica python, existe el valor 'VERDADEOR' y el valor 'FALSE', por lo que se debería convertir esos valores de a True y False respetivamente

In [7]:
# inspeccionmos la columna de tamaño por si existe alguna inconsistencia como las columnas anteriores
base_productos['tamaño'].unique()

array(['Chico', 'Grande', 'Mediano', 'Solo', 'Unitario', 'Porción'],
      dtype=object)

Vemos que esta columna no tiene ninguna inconsistencia en cuanto a sus categorias de tamaños, ya que no hay ninguna repetida.