In [11]:
import os
if os.path.basename(os.getcwd()) == "inspeccion":
    os.chdir("..")
    
import pandas as pd
from utils.funciones_filtrado import unicos_x_columna, tipo_nulo_unicos_x_columna

In [12]:
base_clientes = pd.read_excel('clientes.xlsx')
base_clientes.head()

,cliente_id,nombre,correo,telefono,fecha_registro,ciudad,puntos
0,C0001,Ana López,ana.lopez@gmail.com,2227365745,2024-08-17,Puebla,51
1,C0002,Carlos Mendoza,carlos.mendoza@,222291,2024-07-15,Cholula,134
2,C0003,María García,maria.garciagmail.com,NaN,2023-12-18,Atlixco,187
3,C0004,José Hernández,jose.hernandezgmail.com,2228031212,2024-12-18,Tehuacán,385
4,C0005,Laura Torres,correo_invalido,no tengo,2023-10-14,Puebla,230

In [13]:
#obtenemos su tamaño
no_registros, no_columnas = base_clientes.shape
print(f"Número de clientes registrados: {no_registros}, número de columnas de la tabla: {no_columnas}")

Número de clientes registrados: 128, número de columnas de la tabla: 7

Desde una inpección rápida ya podemos observar que en la columna 'correo' existen correos mal registrados, la columna 'telefono' no están completos los telefonos, son nulos o escribieron otra cosa.

In [14]:
inspeccion = tipo_nulo_unicos_x_columna(base_clientes)
inspeccion

,columna,tipo de dato,cantidad de valores nulos,cantidad de valores unicos
0,cliente_id,object,0,128
1,nombre,object,4,15
2,correo,object,20,41
3,telefono,object,23,74
4,fecha_registro,object,0,112
5,ciudad,object,0,5
6,puntos,int64,0,112

Corroborramos que la columna 'telefono' no es un tipo 'int64', es decir, no sólo contiene números, como era de esperarse, caso contrario a la columna 'puntos' que efectivamente su tipo si es númerico; además la columna 'fecha_registro' tampoco está con el tipo de dato de fecha que sería un 'datetime64'

En la segunda columna podemos observar algo muy importante, notamos que ciertas columnas tienen bastante valores nulos, es decir, que no existe ningún valor para ese registro, por ejemplo, la columna de correo existen 20 clientes que no proporcionaron su correo, de la misma forma hay 23 clientes que no tenemos su número telefónico.

En la tercera columna, notamos que efectivamente tenemos 128 id's de clientes que justo coincide con el número de registros en la base, pero algo que no llega a concordar es que sólo existen 15 nombres diferentes, cuando se espera que existan 128 clientes con nombres diferentes, es decir, hay nombres repetidos con diferente id, cuando para un mismo cliente, el id debería ser el mismo.

In [ ]:
#rectificamos los nombre de la ciudad
base_clientes['ciudad'].unique()

array(['Puebla', 'Cholula', 'Atlixco', 'Tehuacán', 'San Andrés'],
      dtype=object)

In [16]:
#Obtenemos los nombres de los clientes unicos, es decir sin repetición
base_clientes['nombre'].unique()

array(['Ana López', 'Carlos Mendoza', 'María García', 'José Hernández',
       'Laura Torres', 'Roberto Díaz', 'Sofía Ramírez', 'Pedro Morales',
       'Diana Cruz', 'Miguel Flores', 'Lucía Martínez', 'Fernando Ruiz',
       'Valentina Soto', nan, 'Camila Vargas', 'Andrés Jiménez'],
      dtype=object)

In [17]:
#Filtramos a la primera clienta 'Ana López' para observar que está pasando con ella y porque se repite su nombre

cliente_Ana = base_clientes[base_clientes['nombre'] == 'Ana López']
cliente_Ana

,cliente_id,nombre,correo,telefono,fecha_registro,ciudad,puntos
0,C0001,Ana López,ana.lopez@gmail.com,2227365745,2024-08-17,Puebla,51
15,C0016,Ana López,ana.lopez@,NaN,2024-10-27,Puebla,332
30,C0031,Ana López,correo_invalido,2221479346,2023-02-05,Puebla,339
45,C0046,Ana López,ana.lopez@gmail.com,2224060284,2023-05-20,Puebla,148
60,C0061,Ana López,NaN,2222894625,2023-08-30,Puebla,324
75,C0076,Ana López,ana.lopez@gmail.com,NaN,2024-01-08,Puebla,397
90,C0091,Ana López,ana.lopezgmail.com,2223798595,2023-07-04,Puebla,281
105,C0106,Ana López,correo_invalido,222456,2024-03-20,Puebla,213

In [18]:
print(f'La clienta "Ana Lopéz" se registro: {len(cliente_Ana)} veces ')

La clienta "Ana Lopéz" se registro: 8 veces

In [19]:
print('Número de valores únicos por cada columna')
unicos_x_columna(cliente_Ana)

Número de valores únicos por cada columna

          columna  cantidad de valores unicos
0      cliente_id                           8
1          nombre                           1
2          correo                           4
3        telefono                           6
4  fecha_registro                           8
5          ciudad                           1
6          puntos                           8

Notamos que la clienta 'Ana López' ha tenido 8 registros en total, pero en todos los registros de ellos ha registrado 6 teléfonos diferente, 4 correos distintos, por lo que el supuesto que yo hago para el caso de los 15 clientes es que su registro se repitió ya que su nombre es el mismo y para ser que que compran en la misma tienda.

In [20]:
no_numero = base_clientes[pd.to_numeric(base_clientes['telefono'], errors='coerce').isna()]
no_numero.head()

,cliente_id,nombre,correo,telefono,fecha_registro,ciudad,puntos
2,C0003,María García,maria.garciagmail.com,NaN,2023-12-18,Atlixco,187
4,C0005,Laura Torres,correo_invalido,no tengo,2023-10-14,Puebla,230
5,C0006,Roberto Díaz,roberto.diaz@gmail.com,NaN,2024-12-03,Puebla,117
8,C0009,Diana Cruz,diana.cruz@gmail.com,no tengo,2024-05-26,San Andrés,68
9,C0010,Miguel Flores,correo_invalido,NaN,2024-06-30,Puebla,368

Hacemos una inspección a la columna 'telefono' y notamos que hay entradas de tipo texto