In [27]:
import os
if os.path.basename(os.getcwd()) == "limpieza":
    os.chdir("..")
    
import pandas as pd
import numpy as np
from utils.funciones_filtrado import tipo_nulo_unicos_x_columna

In [28]:
base_campanas = pd.read_excel('campanas.xlsx')
base_campanas.head()

,campaña,fecha_inicio,fecha_fin,canal,presupuesto,sucursal,ventas_generadas
0,Bienvenida 2024,2024-01-01,2024-01-31,Redes Sociales,5000.0,Puebla Centro,85000.0
1,San Valentín,2024-02-01,2024-02-15,Email,3000.0,Puebla centro,NaN
2,Café de Marzo,2024-03-01,2024-03-31,redes sociales,4500.0,Angelópolis,72000.0
3,Primavera,2024-03-15,2024-04-15,Flyer,NaN,ANGELOPOLIS,61000.0
4,Día del Niño,2024-04-20,2024-04-30,Redes Sociales,2000.0,Cholula,38000.0

Vamos a estandarizar las columnas de canal y sucursal, ya que encontramos inconsistencias.

In [29]:
base_campanas['canal'] = base_campanas['canal'].str.lower().str.strip() 
base_campanas['sucursal'] = base_campanas['sucursal'].str.lower().str.strip() 

base_campanas['sucursal'] = np.where(base_campanas['sucursal'].str.startswith('a'), 'angelopolis', base_campanas['sucursal'])

Para llenar los valores faltantes, supondremos que serán las medias de cada columna, debido a que tenemos pocos datos, y como es una analisis rápido, creo que es la mejor opción.

In [30]:
media_presupuesto = round(base_campanas['presupuesto'].mean(), 2)
media_ventas = round(base_campanas['ventas_generadas'].mean(), 2)

base_campanas['presupuesto'] = base_campanas['presupuesto'].fillna(media_presupuesto)
base_campanas['ventas_generadas'] = base_campanas['ventas_generadas'].fillna(media_ventas)

base_campanas

,campaña,fecha_inicio,fecha_fin,canal,presupuesto,sucursal,ventas_generadas
0,Bienvenida 2024,2024-01-01,2024-01-31,redes sociales,5000.00,puebla centro,85000.0
1,San Valentín,2024-02-01,2024-02-15,email,3000.00,puebla centro,87600.0
2,Café de Marzo,2024-03-01,2024-03-31,redes sociales,4500.00,angelopolis,72000.0
3,Primavera,2024-03-15,2024-04-15,flyer,4722.22,angelopolis,61000.0
4,Día del Niño,2024-04-20,2024-04-30,redes sociales,2000.00,cholula,38000.0
5,Verano Frío,2024-06-01,2024-08-31,email,8000.00,todas,195000.0
6,Regreso a Clases,2024-08-01,2024-08-31,redes sociales,3500.00,puebla norte,54000.0
7,Octubre Fest,2024-10-01,2024-10-31,flyer,2500.00,san andres,42000.0
8,Día de Muertos,2024-10-25,2024-11-05,email,4722.22,cholula,31000.0
9,Navidad,2024-12-01,2024-12-31,redes sociales,10000.00,puebla centro,210000.0
10,Fin de Año,2024-12-20,2025-01-05,email,4000.00,todas,88000.0

In [31]:
inspeccion = tipo_nulo_unicos_x_columna(base_campanas)
inspeccion

,columna,tipo de dato,cantidad de valores nulos,cantidad de valores unicos
0,campaña,object,0,11
1,fecha_inicio,object,0,11
2,fecha_fin,object,0,10
3,canal,object,0,3
4,presupuesto,float64,0,10
5,sucursal,object,0,6
6,ventas_generadas,float64,0,11

In [32]:
base_campanas.to_excel('campanas_limpio.xlsx', index=False)