In [2]:
import os
if os.path.basename(os.getcwd()) == "limpieza":
    os.chdir("..")
    
import pandas as pd
import numpy as np

In [16]:
base_clientes = pd.read_excel('clientes.xlsx')
base_clientes

,cliente_id,nombre,correo,telefono,fecha_registro,ciudad,puntos
0,C0001,Ana López,ana.lopez@gmail.com,2227365745,2024-08-17,Puebla,51
1,C0002,Carlos Mendoza,carlos.mendoza@,222291,2024-07-15,Cholula,134
2,C0003,María García,maria.garciagmail.com,NaN,2023-12-18,Atlixco,187
3,C0004,José Hernández,jose.hernandezgmail.com,2228031212,2024-12-18,Tehuacán,385
4,C0005,Laura Torres,correo_invalido,no tengo,2023-10-14,Puebla,230
...,...,...,...,...,...,...,...
123,C0214,Roberto Díaz,roberto.diaz@gmail.com,NaN,2024-12-03,Puebla,378
124,C0231,José Hernández,jose.hernandezgmail.com,2228031212,2024-12-18,Tehuacán,485
125,C0218,NaN,NaN,no tengo,2024-05-03,Puebla,444
126,C0236,Diana Cruz,diana.cruzgmail.com,2228887754,2023-07-05,San Andrés,7
127,C0288,Sofía Ramírez,NaN,222827,2023-10-01,Cholula,411

Por el primer supuesto vamos a quedarnos con un sólo registro de cada cliente, priorizando el registro donde tenga mayor cantidad de puntos.

In [18]:
base_clientes = base_clientes.sort_values(by='puntos', ascending=False)
base_clientes = base_clientes[~base_clientes['nombre'].duplicated(keep='first')]
base_clientes['fecha_registro'] = pd.to_datetime(base_clientes['fecha_registro'])
base_clientes['nombre'] = base_clientes['nombre'].fillna('Sin Nombre')
base_clientes['telefono'] = pd.to_numeric(base_clientes['telefono'], errors='coerce').fillna(0)
base_clientes

,cliente_id,nombre,correo,telefono,fecha_registro,ciudad,puntos
31,C0032,Carlos Mendoza,carlos.mendoza@gmail.com,0,2024-04-23,Cholula,499
14,C0015,Camila Vargas,camila.vargas@gmail.com,222988,2024-11-26,Cholula,493
86,C0087,Fernando Ruiz,correo_invalido,222179,2023-08-10,Puebla,491
95,C0096,Roberto Díaz,roberto.diaz@gmail.com,0,2024-04-03,Puebla,491
124,C0231,José Hernández,jose.hernandezgmail.com,2228031212,2024-12-18,Tehuacán,485
94,C0095,Laura Torres,laura.torres@,2227292514,2024-07-17,Puebla,474
125,C0218,Sin Nombre,NaN,0,2024-05-03,Puebla,444
10,C0011,Lucía Martínez,lucia.martinezgmail.com,222356,2024-07-29,Cholula,439
92,C0093,María García,maria.garcia@gmail.com,0,2023-11-29,Atlixco,432
84,C0085,Miguel Flores,miguel.flores@gmail.com,222671,2024-03-01,Puebla,420
43,C0044,Andrés Jiménez,andres.jimenezgmail.com,2229667278,2024-09-19,Puebla,413
127,C0288,Sofía Ramírez,NaN,222827,2023-10-01,Cholula,411
75,C0076,Ana López,ana.lopez@gmail.com,0,2024-01-08,Puebla,397
22,C0023,Pedro Morales,pedro.morales@gmail.com,0,2024-01-07,Puebla,382
68,C0069,Diana Cruz,NaN,0,2024-01-02,San Andrés,370
57,C0058,Valentina Soto,valentina.soto@gmail.com,0,2024-02-03,Atlixco,348

In [19]:
base_clientes.dtypes

cliente_id                object
nombre                    object
correo                    object
telefono                   int64
fecha_registro    datetime64[ns]
ciudad                    object
puntos                     int64
dtype: object